# name: Deploy on DigitalOcean

# on:
#   push:
#     branches: [main]


# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Pull repo
#         uses: aapleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.DO_HOST }}
#           username: ${{ secrets.DO_USERNAME }}
#           password: ${{ secrets.DO_PASSWORD }}
#           script: |
#             cd /home/dhiraj/capi-backend/capi-backend
#             pm2 stop capi-staging
#             git pull origin main
#             npm install
#             pm2 start capi-staging